# docker-compose.yml
version: '3.8'

services:
  app:
    build: 
      context: ..
      dockerfile: setup/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/phonebook?sslmode=disable
    networks:
      - phonebook-network
    

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=phonebook
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ../database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - phonebook-network
  

volumes:
  postgres-data:

networks:
  phonebook-network:
    driver: bridge